### ISSUE TITLE
Problem with reference that matches file name

### ISSUE THREAD

**Issue by franksl** [thephpleague/json-reference#15] opened 2017-11-24 12:05 UTC
Hi,
I get an error with this reference:
`{"$ref": "./triggerActions.json#/triggerAction"}`

where triggerActions.json is defined as:
```
{
    {
        "triggerAction": { ... }
    }
}
```

The resolver tries to look at the file: actionss.json and gives an error
I think the problem lies in functions.php at the function strip_fragment where it replaces the wrong string.
Thanks,
Franco

**Comment by matt-allan** [comment] 2017-11-24 13:29
Hello,

It's hard to tell how to reproduce the issue from the bug report.  Could you post the error?  How was the initial file loaded that contains the reference?

**Comment by franksl** [comment] 2017-11-27 13:15
Sorry, I was very busy and this bug took a lot of time to be found, here's the procedure to reproduce it:

1. Create a file named _schema.json_ with this content:
```
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "testProp": {"$ref": "./triggerActions.json#/triggerAction"}
    }
}
```

2. Create a file named _triggerActions.json_ with this content:
```
{
    "triggerAction": {
        "type": "object",
        "properties": {
            "test": {"type": "integer"}
        }
    }
}
```

3. Execute the following php script:
```
<?php

require_once('vendor/autoload.php');

$dereferencer  = \League\JsonReference\Dereferencer::draft4();
$schema        = $dereferencer->dereference('file://./schema.json');
$data          = json_decode('{ "testProp": {"test": 11 }}');

$validator     = new \League\JsonGuard\Validator($data, $schema);

if ($validator->fails()) {
    $errors = $validator->errors();
    foreach ($errors as $e) {
        print_r(json_encode($e));
    }
} else {
    print_r('OK');
}
```

This is the error I get:
```
PHP Fatal error:  Uncaught League\JsonReference\SchemaLoadingException: The schema ".s.json" could not be found. in /var/www/html/bugref/vendor/league/json-reference/src/SchemaLoadingException.php:14
Stack trace:
#0 /var/www/html/bugref/vendor/league/json-reference/src/Loader/FileLoader.php(31): League\JsonReference\SchemaLoadingException::notFound('.s.json')
#1 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(181): League\JsonReference\Loader\FileLoader->load('.s.json')
#2 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(84): League\JsonReference\Dereferencer->loadExternalRef('file://./trigge...')
#3 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(160): League\JsonReference\Dereferencer->prepareArguments('file://./trigge...', 'file://./trigge...')
#4 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(71): League\JsonReference\Dereferencer->crawl('file://./trigge...', '', Object(Closure))
#5 /var/www/html/bugref/vendor/league/json-reference/ in /var/www/html/bugref/vendor/league/json-reference/src/SchemaLoadingException.php on line 14
```

As I said there is some problem in the strip_fragment function as it recognizes the string "triggerAction" in the wrong place. If I change the name of the property triggerAction everything works correctly

**Comment by matt-allan** [comment] 2017-11-27 15:07
Thanks for the detailed reproduction steps, that is very helpful 👍 

Can you try installing dev-master and see if the issue goes away?  I can't reproduce on master and this looks like the same issue that was fixed by #7.

**Comment by franksl** [comment] 2017-11-27 15:27
I checked out dev-master through composer, same error with a slight different path:
```
PHP Fatal error:  Uncaught League\JsonReference\SchemaLoadingException: The schema "file://./schema.json" could not be found. in /var/www/html/bugref/vendor/league/json-reference/src/SchemaLoadingException.php:14
Stack trace:
#0 /var/www/html/bugref/vendor/league/json-reference/src/Loader/FileLoader.php(33): League\JsonReference\SchemaLoadingException::notFound('file://./schema...')
#1 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(181): League\JsonReference\Loader\FileLoader->load('./schema.json')
#2 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(84): League\JsonReference\Dereferencer->loadExternalRef('file://./schema...')
#3 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(160): League\JsonReference\Dereferencer->prepareArguments('file://./schema...', 'file://./schema...')
#4 /var/www/html/bugref/vendor/league/json-reference/src/Dereferencer.php(71): League\JsonReference\Dereferencer->crawl('file://./schema...', '', Object(Closure))
#5 /var/www/html/bugref in /var/www/html/bugref/vendor/league/json-reference/src/SchemaLoadingException.php on line 14
```

**Comment by matt-allan** [comment] 2017-11-27 16:04
Oh, you also need to change `'file://./schema.json'` to `'file://' . __DIR__ . '/schema.json'` (assuming you are on *nix).  `'file://./schema.json'` is not a valid URI so it won't load correctly.

**Comment by franksl** [comment] 2017-11-27 16:56
Sorry, my mistake, it works on dev-master now, thanks!

**Comment by matt-allan** [comment] 2017-11-27 17:00
Great 😄 

I'm going to close this, but feel free to reopen it if you have any further issues.  There should be a minor release coming out soon.

**Closed as completed by matt-allan** 2017-11-27 17:00 UTC
